# Generated by Django 5.2.6 on 2025-09-27 09:06

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("careers_jobs", "0001_initial"),
        ("careers_tags", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="skills",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Required skills",
                through="careers_tags.JobTag",
                to="taggit.Tag",
                verbose_name="skills",
            ),
        ),
        migrations.AddField(
            model_name="formfield",
            name="job",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_fields",
                to="careers_jobs.job",
            ),
        ),
    ]
