# Generated by Django 5.2.4 on 2025-09-19 08:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("careers_jobs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="details",
            field=wagtail.fields.StreamField(
                [
                    ("code", 5),
                    ("quote", 6),
                    ("paragraph", 7),
                    ("video", 8),
                    ("image", 9),
                    ("document", 10),
                    ("accordion", 18),
                    ("alert", 29),
                    ("carousel", 35),
                    ("diff", 38),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide which programming language is used",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide copy buttons",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Wether to show or hide window buttons",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("auto", "Auto"),
                                ("bash", "Bash"),
                                ("c", "C"),
                                ("cpp", "C++"),
                                ("csharp", "C#"),
                                ("css", "CSS"),
                                ("dart", "Dart"),
                                ("dockerfile", "Dockerfile"),
                                ("go", "Go"),
                                ("html", "HTML"),
                                ("java", "Java"),
                                ("javascript", "JavaScript"),
                                ("json", "JSON"),
                                ("kotlin", "Kotlin"),
                                ("lua", "Lua"),
                                ("markdown", "Markdown"),
                                ("php", "PHP"),
                                ("python", "Python"),
                                ("ruby", "Ruby"),
                                ("rust", "Rust"),
                                ("scss", "SCSS"),
                                ("shell", "Shell"),
                                ("sql", "SQL"),
                                ("swift", "Swift"),
                                ("typescript", "TypeScript"),
                                ("xml", "XML"),
                                ("yaml", "YAML"),
                                ("plaintext", "Plain text"),
                            ],
                            "help_text": "Programming language",
                        },
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Code content", "required": True},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("show_language", 0),
                                ("show_copy_btn", 1),
                                ("show_window_btns", 2),
                                ("language", 3),
                                ("code", 4),
                            ]
                        ],
                        {"help_text": "Code"},
                    ),
                    6: ("wagtail.blocks.BlockQuoteBlock", (), {"help_text": "Quote"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                    8: ("wagtail.embeds.blocks.EmbedBlock", (), {"help_text": "Video"}),
                    9: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Image"}),
                    10: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document"},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Accordion name",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("plus", "Plus"), ("arrow", "Arrow")],
                            "help_text": "Style variant",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Wether to show or hide item content",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Item title", "max_length": 64, "required": True},
                    ),
                    15: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Item content", "required": True},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("is_expanded", 13), ("title", 14), ("content", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (16,),
                        {"help_text": "Accordion items", "required": True},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 11), ("variant", 12), ("items", 17)]],
                        {"help_text": "Accordion"},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "alert-triangle",
                            "help_text": "Icon name (lucide icons)",
                            "max_length": 32,
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if article is vertical or horizontal (default)",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("soft", "Soft"), ("outline", "Outline")],
                            "help_text": "Style variant",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("success", "Success"),
                                ("warning", "Warning"),
                                ("error", "Error"),
                            ],
                            "help_text": "Alert level",
                        },
                    ),
                    23: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "code",
                                "superscript",
                                "subscript",
                                "strikethrough",
                            ],
                            "help_text": "Alert message",
                            "required": True,
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Action label",
                            "max_length": 32,
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Action internal link", "required": False},
                    ),
                    26: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Action external link", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 24), ("page", 25), ("url", 26)]],
                        {"help_text": "Alert action", "required": False},
                    ),
                    28: (
                        "wagtail.blocks.ListBlock",
                        (27,),
                        {"help_text": "Alert actions", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 19),
                                ("is_vertical", 20),
                                ("variant", 21),
                                ("level", 22),
                                ("message", 23),
                                ("actions", 28),
                            ]
                        ],
                        {"help_text": "Alert"},
                    ),
                    30: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Designates if carousel is vertical or horizontal (default)",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "Video", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Caption", "max_length": 128, "required": False},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 9), ("video", 31), ("caption", 32)]],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.ListBlock",
                        (33,),
                        {"help_text": "Carousel items", "required": True},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("is_vertical", 30), ("items", 34)]],
                        {"help_text": "Carousel"},
                    ),
                    36: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Diff Item 1"},
                    ),
                    37: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"help_text": "Diff Item 2"},
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("item_1", 36), ("item_2", 37)]],
                        {"help_text": "Diff"},
                    ),
                },
                help_text="Job details",
                verbose_name="details",
            ),
        ),
    ]
