# Generated by Django 5.2.6 on 2025-09-27 08:50

import careers.apps.mixins
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0098_remove_searchpromotion_query_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Category description",
                        null=True,
                        verbose_name="description",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(careers.apps.mixins.ChildPaginatorMixin, "wagtailcore.page"),
        ),
    ]
